[package]
name = "oauth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = ">=0.8"
http = ">=0.2"
warp = ">=0.3"
base64 = ">=0.21"
urlencoding = ">=2.1"
serde_json = ">=1"
time = ">=0.3"
